api:
  debug: true
  host: localhost
  port: 8000
data:
  cache_enabled: true
  cache_ttl: 3600
  history_days: 365
  symbols:
  - EURUSD
  timeframes:
  - M1
  - M5
database:
  echo: false
  url: sqlite:///data/trading_bot.db
environment: development
logging:
  backup_count: 5
  file: logs/trading_bot.log
  level: INFO
  max_size: 100MB
ml:
  feature_lookback: 100
  model_retrain_days: 30
  random_state: 42
  validation_split: 0.2
mt5:
  login: 12605399
  password: gY81bI*L
  server: BlueberryMarkets-Demo
  timeout: 10000
trading:
  fibonacci_levels:
    extensions:
    - 1.0
    - 1.272
    - 1.618
    - 2.0
    retracements:
    - 0.236
    - 0.382
    - 0.5
    - 0.618
    - 0.786
  max_daily_loss: 0.05
  max_positions: 3
  risk_per_trade: 0.01
